# Generated by Django 5.2.12 on 2026-03-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest_drop_lat_servicerequest_drop_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('Truck', 'KHAHAULER'), ('Bike', 'KHARIDER'), ('Foot courier', 'KHARUNNER')], max_length=20),
        ),
    ]
