# Generated by Django 5.2.12 on 2026-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_businessimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='reciever_phone_number',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='sender_phone_number',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
