# Generated by Django 5.2.12 on 2026-03-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicerequest_reciever_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('Truck', 'KHASHAULER'), ('Bike', 'KHASRIDER'), ('Foot courier', 'KHASRUNNER')], max_length=20),
        ),
    ]
