# Generated by Django 5.2.12 on 2026-03-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicerequest_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='reciever_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='sender_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('Truck', 'KHASHAULER'), ('Dispatch rider', 'KHASRIDER'), ('Foot courier', 'KHASRUNNER')], max_length=20),
        ),
    ]
