# Generated by Django 5.2.12 on 2026-03-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_servicerequest_reciever_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='reciever_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
