# Generated by Django 5.2.12 on 2026-03-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_servicerequest_reciever_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='package_description',
            field=models.CharField(default='Item', max_length=255),
        ),
    ]
