# Generated by Django 5.2.12 on 2026-03-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_servicerequest_package_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='reciever_name',
            new_name='receiver_name',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='reciever_phone_number',
            new_name='receiver_phone_number',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='weight_kg',
            new_name='weight',
        ),
    ]
