# Generated by Django 5.2.12 on 2026-03-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_reciever_name_servicerequest_receiver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='receiver_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='sender_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
