# Generated by Django 5.2.12 on 2026-03-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_status',
            field=models.BooleanField(default='pending'),
        ),
    ]
