# Generated by Django 5.2.12 on 2026-03-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_servicerequest_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='KHASIS EXPRESS', max_length=200)),
                ('subtitle', models.CharField(default='Fast, Reliable Delivery Across Lagos', max_length=300)),
                ('background_image', models.ImageField(upload_to='landing_images/')),
            ],
        ),
    ]
