# Generated by Django 5.2.12 on 2026-04-01 20:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_landingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='background_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='subtitle',
            field=models.CharField(default='Swift, Reliable Delivery Across Lagos', max_length=300),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
