# Generated by Django 5.2.12 on 2026-04-02 20:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_landingpage_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
